### ISSUE TITLE
A Strange Behavior of `NewVector`

### ISSUE THREAD

**Issue by zhenghaoz** [gorgonia/gorgonia#249] opened 2018-11-08 10:16 UTC
Hi. I found something strange when using `NewVector`.  When I create two vectors in a row:

```go
g := gorgonia.NewGraph()
a := gorgonia.NewVector(g, gorgonia.Float64, gorgonia.WithShape(2))
b := gorgonia.NewVector(g, gorgonia.Float64, gorgonia.WithShape(2), 
    gorgonia.WithInit(gorgonia.Zeroes()))
fmt.Println(a.Value(), b.Value())
gorgonia.Let(a, tensor.New(tensor.WithShape(2), tensor.WithBacking([]float64{1,2})))
fmt.Println(a.Value(), b.Value())
```
The output indicates that the two vectors share the memory space.
```
<nil> <nil>
[1  2] [1  2]
```
However, if I give different names to two vectors:
```go
g := gorgonia.NewGraph()
a := gorgonia.NewVector(g, gorgonia.Float64, gorgonia.WithName("a"), gorgonia.WithShape(2))
b := gorgonia.NewVector(g, gorgonia.Float64, gorgonia.WithName("b"), gorgonia.WithShape(2), 
    gorgonia.WithInit(gorgonia.Zeroes()))
fmt.Println(a.Value(), b.Value())
gorgonia.Let(a, tensor.New(tensor.WithShape(2), tensor.WithBacking([]float64{1,2})))
fmt.Println(a.Value(), b.Value())
```
They have individual memory spaces.
```
<nil> [0  0]
[1  2] [0  0]
```
 
It seems that:
- They share the memory space if they have the same shape or name.
- Otherwise, they have individual memory spaces.

Is it a bug or something wrong by myself? It's really strange.

The version is:

```
gorgonia.org/gorgonia v0.9.0-beta.0.20181027224840-11edd62a505a
```

Thanks a lot :D

**Comment by owulveryck** [comment] 2018-11-09 06:44
I will have a closer look, but it looks like that it is a duplicate of [#87](https://github.com/gorgonia/gorgonia/issues/87)

**Comment by owulveryck** [comment] 2018-11-09 20:49
Closing as this issue is definitely related to issue 87.

**Closed by owulveryck** 2018-11-09 20:49 UTC
