### ISSUE TITLE
Running convnet example does even complete one epoch

### ISSUE THREAD

**Issue by tantanchen** [gorgonia/gorgonia#189] opened 2018-01-15 17:22 UTC
The problem starts here in main.go: line 269
			if err = xVal.(*tensor.Dense).Reshape(bs, 1, 28, 28); err != nil {
I believe the underlying problem is in tensor/dense.go: line 130
	if t.old != nil {
		t.Transpose()
	}
When t.old != nil, it takes a while to Transpose(). This is suspicious because we maintain the old *AP to untranspose, so it shouldn't take that long.
Next steps:
- I don't actually know how t.old get set. I couldn't find it yet, so I'll keep looking.
- If t.old was correctly set, then I think the problem is in Transpose() where it is not untransposing to the old *AP

**Comment by chewxy** [comment] 2018-01-15 22:57
This got fucked in the transition to 0.8.0, when I "optimized" the Transposes. I'll look into this to see how to fix it.

**Comment by tantanchen** [comment] 2018-01-16 16:18
If you have time, can you show me the trouble shooting techniques you use? After digging around, I feel a little more comfortable with the code, but I'm just putting Println()'s every where to see which lines are running. I would like to get to a point where I can actually help fix some of the issues.

**Comment by chewxy** [comment] 2018-01-16 19:40
Sure. Step 1 for me is to usually identify if the coding of the neural network is errorneous. To do that I use the publicly available APIs: 

## Add loggers to machines ##

```
logger := log.New(os.Stderr, "", 0) 
m0 := G.NewLispMachine(graph, G.WithLogger(logger), G.WithWatchlist(), G.LogBothDir())
m1 := G.NewTapeMAchine(graph, G.WithLogger(logger), G.WithWatchlist())
```
If I find out it's a problem with the coding of the NN, then i add specific nodes to the `Watchlist` to actually only observe those. There are [other logging options](https://godoc.org/gorgonia.org/gorgonia#VMOpt) which may be useful. I found them useful 99% of the time.

## Enter debug Mode ## 

Sometimes it's the library that has bugs. Gorgonia comes with a built in debug mode. To do that I run the code with build tags: `go run -tags=debug *.go`. If you want to run multiple build modes do something like `go run -tags=debug,cude *.go`.

Now with debug mode, there are classes of things to debug, that can be turned on or off. They can be found [https://github.com/gorgonia/gorgonia/blob/master/debug.go](here). In large swarths:

* Compilation
* Shape Inference
* Type System
* Symbolic DIfferentiation
* Automatic Differentiation
* VM executions
* CUDA executions
* Allocator executions

To enable logging/tracing for those "components" you'd have to set the debug value to `true`. It's useful for library development.

Most code is annotated that you can see a trace. The functions `enterLoggingContext` and `leaveLoggingContext` are used to denote entering and leaving logging scope. Entering a logging scope simply adds a `\t` to the logs. 

Indeed I found this method much more useful than using Delve (although I occasionally switch to it for step thru), that I abstracted this out into a separate package - [InkHuffer](https://godoc.org/github.com/chewxy/InkHuffer) (Gorgonia isn't using InkHuffer tho)

**Comment by chewxy** [comment] 2018-01-20 12:54
Hm... I've worked out the cause of this - since moving to the v0.8.0 architecture, the cost for inplace transpose is a little greater than expected now. I'm working on a separate solution for this that will allow for allocatey transposes

**Comment by chewxy** [comment] 2018-01-20 14:24
Fixes are in and will be merged.There will be a version bump to v0.8.1, of which the tensor subpackage will share. I'll package up the commits tomorrow.

**Closed** 2018-01-22 03:31 UTC
