### ISSUE TITLE
gonum build issue

### ISSUE THREAD

**Issue by lc-chrisbarton** [gorgonia/gorgonia#251] opened 2018-11-21 18:40 UTC
Using v0.9.0-beta with Go modules

```
# gorgonia.org/gorgonia
go/pkg/mod/gorgonia.org/gorgonia@v0.8.4/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
go/pkg/mod/gorgonia.org/gorgonia@v0.8.4/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
```

Using v0.8.4

```
vendor/gorgonia.org/gorgonia/node.go:436:16: n.shape.CalcStrides undefined (type tensor.Shape has no field or method CalcStrides)
vendor/gorgonia.org/gorgonia/utils.go:137:28: undefined: tensor.InfChecker
vendor/gorgonia.org/gorgonia/utils.go:180:28: undefined: tensor.NaNChecker
vendor/gorgonia.org/gorgonia/walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
vendor/gorgonia.org/gorgonia/walker.go:53:33: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.Sort:
	*ExprGraph does not implement graph.Directed (wrong type for From method)
		have From(int64) []graph.Node
		want From(int64) graph.Nodes
```

**Comment by owulveryck** [comment] 2018-11-21 19:38
I have a PR opened for the branch v0.9.0 regarding this change of the Gonum API: https://github.com/gorgonia/gorgonia/pull/241

**Comment by owulveryck** [comment] 2019-08-22 12:31
Closing this as it is probably not relevant anymore;
feel free to repoen it if the issue is still present

**Closed by owulveryck** 2019-08-22 12:31 UTC
